### ISSUE TITLE
Graceful handling when stop task cannot find running instance

### ISSUE THREAD

**Issue by roberttaylor426** [sourcemuse/GradleMongoPlugin#12]
Currently it spits out an ugly stacktrace.

**Comment by sfitts** [comment]
I seem to be getting this on a routine basis when using `startManagedMongoDb`.  Not sure why since it should be able to find the running instance, perhaps it is trying to do the shutdown twice for some reason.  This started happening when I updated to `0.6.0`.

**Comment by roberttaylor426** [comment]
I believe the issue you are referring to has been fixed in 0.7.0, please give it a try and let me know.

This particular issue is a separate problem and is still valid.

**Comment by sfitts** [comment]
Will do -- thanks.

**Comment by roberttaylor426** [comment]
This no longer seems to be an issue.
