### ISSUE TITLE
Deploy to Gradle Plugin Portal

### ISSUE THREAD

**Issue by roberttaylor426** [sourcemuse/GradleMongoPlugin#13]

**Comment by roberttaylor426** [comment]
See https://plugins.gradle.org/plugin/com.sourcemuse.mongo.

**Comment by jochenberger** [comment]
Great. I suggest you put the term "MongoDB" into the description, currently you won't find the plugin when searching for that from the plugin portal: https://plugins.gradle.org/search?term=mongodb

**Comment by roberttaylor426** [comment]
Good idea.

**Comment by roberttaylor426** [comment]
Do you know if there's a way to edit plugin metadata once it's been published to the portal?

**Comment by jochenberger** [comment]
No, I don't, sorry. Maybe from https://bintray.com/bintray/jcenter/com.sourcemuse.gradle.plugin%3Agradle-mongo-plugin/view?

**Comment by roberttaylor426** [comment]
Alas it doesn't appear to be possible. I'll add the tag in the next release.

Quick - request a feature! :-)

On 3 May 2016 at 10:00, jochenberger <notifications@github.com> wrote:

> No, I don't, sorry. Maybe from
> https://bintray.com/bintray/jcenter/com.sourcemuse.gradle.plugin%3Agradle-mongo-plugin/view
> ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/sourcemuse/GradleMongoPlugin/issues/13#issuecomment-216472733>
>



-- 
Robert
