### ISSUE TITLE
How to Daemonize 'startManagedMongoDb'

### ISSUE THREAD

**Issue by phasebash** [sourcemuse/GradleMongoPlugin#14]
I'm looking to run an embedded MongoDB alongside integration tests and thus would like to have MongoDB up before the tests start.  However, in my current Gradle project, the build is stuck on the `startManagedMongoDb` task and does not continue from there.  I would expect to run `./gradlew startManagedMongoDb test` and have the build run to completion.

Is this use case supported?

**Comment by roberttaylor426** [comment]
This use case is absolutely supported. Where exactly does it get stuck? Could you share your logs? 

Bear in mind that the first time the plugin runs for a specified Mongo version it will need to go away and download the Mongo binaries. Perhaps this is what your build is in the process of doing?

**Comment by phasebash** [comment]
You're absolutely right.  This was not evident to me until I ran in `--debug`, I saw the following:

    12:04:46.840 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@5c8870525 pairs: {GET /osx/mongodb-osx-x86_64-2.6.1.tgz HTTP/1.1: null}{User-Agent: Mozilla/5.0 (compatible; Embedded MongoDB; +https://github.com/flapdoodle-oss/embedmongo.flapdoodle.de)}{Host: fastdl.mongodb.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
    12:04:46.959 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@55fdf7f911 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 113005766}{Connection: keep-alive}{Date: Thu, 29 Jan 2015 17:04:47 GMT}{Last-Modified: Mon, 05 May 2014 12:30:34 GMT}{ETag: "85b1c40e5fcbcfb8659de3dcf4084359"}{Accept-Ranges: bytes}{Server: AmazonS3}{X-Cache: Miss from cloudfront}{Via: 1.1 344c0192a2becdfa5c3c6b927653ff8b.cloudfront.net (CloudFront)}{X-Amz-Cf-Id: VCr6fygKpTRbt8rEOE29uv31ChJgRMhfZWGfUvjA4HK9N3Z6ISqmxw==}
    12:04:46.960 [QUIET] [system.out] Download PRODUCTION:OS_X:B64 DownloadSize: 113005766

It would probably be preferable to have a log message in the plugin which notes that Mongo is being downloaded, and that mongo has finished downloading.  After running the `startManagedMongoDb` task again I do see a useful message:

    Extract /Users/brandon/.embedmongo/osx/mongodb-osx-x86_64-2.6.1.tgz START
    Extract /Users/brandon/.embedmongo/osx/mongodb-osx-x86_64-2.6.1.tgz DONE
    [mongod output]note: noprealloc may hurt performance in many applications

Thanks.

**Comment by roberttaylor426** [comment]
Ok that's a little peculiar. 

By default Gradle should print all _QUIET_ log messages to the console. You should therefore have seen that _'Download...'_ message you reported from the `--debug` output printed to the console in the same way that you now see the _'Extract...'_ message printed to the console without specifying the `--debug` option. 

Are you sure you didn't see the downloading message when you ran the build initially? Were you overriding the log level at the time?

If you want to attempt to reproduce the scenario you can either clear your local cache (likely under ~/.embedmongo) or specify a different `mongoVersion` in your build config.

**Comment by roberttaylor426** [comment]
Incidentally I agree the log messages themselves could be spruced up a little. Currently it's all handled by the [Embedded MongDb plugin](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo). If you think the logging could be enhanced that's something we could look at...
