### ISSUE TITLE
It should be possible to configure the command line options for mongod

### ISSUE THREAD

**Issue by jochenberger** [sourcemuse/GradleMongoPlugin#16]
I'd like to be able to enable journalling for my mongod instance. This has to be enabled manually (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/commit/057479c587d22af433c5fe8bad69e633e8d53924#commitcomment-7545135). I haven't found a way to do this with the plugin.

**Comment by roberttaylor426** [comment]
You're right, the plugin doesn't currently support toggling journaling.

Would a __journalingEnabled__ configuration option suffice (defaulting to false)? It looks like it should be straightforward to implement.

**Comment by jochenberger** [comment]
Great, thanks!

**Comment by roberttaylor426** [comment]
Just promoted 0.5.0 to central which supports the __journalingEnabled__ option. Closing this issue.
