### ISSUE TITLE
New Flapdoodle Version 1.47.0 with Mongo 3.0 Support

### ISSUE THREAD

**Issue by kaib** [sourcemuse/GradleMongoPlugin#20]
Hi is it possible to include the newest flapdoodle release to support Mongo 3.0?

**Comment by roberttaylor426** [comment]
Yes, this is quite possible. I've just cut release 0.6.0, which is built on the latest 1.47.0 version of flapdoodle. Expect it to be available on Central within the next few hours.

Happy coding :-)

**Comment by kaib** [comment]
Wow THX for the fast response!

Am 12.03.2015 22:33 schrieb Robert Taylor <notifications@github.com>:

Yes, this is quite possible. I've just cut release 0.6.0, which is built on the latest 1.47.0 version of flapdoodle. Expect it to be available on Central within the next few hours.

Happy coding :-)
