### ISSUE TITLE
Gradle proxy settings seem to be ignored

### ISSUE THREAD

**Issue by dpapathanasiou** [sourcemuse/GradleMongoPlugin#28]
I'm using the Gradle Mongo Plugin in a corporate environment, behind a firewall.

My gradle.properties file contains all the 'systemProp.https.proxy' values I need, normally.

In the buildscript dependencies, I've add this line, defining the internal maven url, under 'mavenCentral()':

``` sh
maven { url 'http://...' }
```

and the classpath dependency matches the latest version available there:

``` sh
classpath 'com.sourcemuse.gradle.plugin:gradle-mongo-plugin:0.8.0'
```

When I run 'gradle tasks', I do see startManagedMongoDb/startMongoDb/stopMongoDb among the output.

But when I try 'gradle startManagedMongoDb' or 'gradle startMongoDb', I get this error, which is b/c of no access to <tt>http://fastdl.mongodb.org/</tt>:

``` sh
:startMongoDb
Downloading Mongo 2.4.3 distribution...
prepare executable
java.io.IOException: Could not open inputStream for http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.4.3.tgz
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
...
```

So is there something explicit I need to do in my gradle build file, above and beyond having proxy settings in gradle.properties?

**Comment by roberttaylor426** [comment]
Good question. No, this is a feature lacking from the plugin at the moment.

If the plugin picked up the `systemProp.https.proxy` properties and used those, I assume that would suit your needs?

**Comment by dpapathanasiou** [comment]
Yes, that would be great, thank you!

**Comment by dpapathanasiou** [comment]
Yes, I did try that. I've since found a work-around, by not using this plugin at all, but if you ever do resolve this, I would be interested in knowing.

**Comment by arudge** [comment]
I can't assign this to myself, but I'm cooking up a PR for adding a config option to specify a proxy for downloads.
