### ISSUE TITLE
Using already started mongodb should not stop the instance

### ISSUE THREAD

**Issue by kaib** [sourcemuse/GradleMongoPlugin#35]
I like the feature that the plugin is reusing a already started mongoDB instance,
but i think in this case it should not close the Instance when the task is finished

I think this is a bug

**Comment by roberttaylor426** [comment]
I would agree with your assessment.

**Comment by roberttaylor426** [comment]
This was fixed in the 0.11.0 release, which was just pushed to Central.

**Comment by kaib** [comment]
Wow i appreciate your fast fix! Kudos
