### ISSUE TITLE
Make versions configurable (de.flapdoodle.embed.mongo, mongo-java-driver)

### ISSUE THREAD

**Issue by juergenzimmermann** [sourcemuse/GradleMongoPlugin#40]
de.flapdoodle.embed.mongo is preconfigured for 1.50.1, the current version is 1.50.5,
mongo-java-driver is preconfigured for 3.2.2, the current version is 3.3.0 resp. 3.4.0-beta1.

It would be fine, if one could override the preconfigured version

**Comment by roberttaylor426** [comment]
Hi,

The mongo-java-driver version _can_ be configured using the `mongoVersion` option. Usage is described in the README. I just ran the tests specifying version `3.3.14` in the build script and they passed.

Could you please explain why you would want to configure the flapdoodle version? What's your use case?

**Comment by roberttaylor426** [comment]
Closing for now. Let me know if you still think there's an improvement to be made.
