### ISSUE TITLE
Expose serverSelectionTimeout

### ISSUE THREAD

**Issue by gnomff** [sourcemuse/GradleMongoPlugin#41]
I am getting this error

> Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
> No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
> Exception in monitor thread while connecting to server 127.0.0.1:27017
> com.mongodb.MongoSocketReadException: Prematurely reached end of stream

which is causing my builds to pause while waiting for the timeout. I would like to be able to set the timeout much lower so that my build won't take so long

**Comment by roberttaylor426** [comment]
What version of the plugin are you using please?

**Comment by roberttaylor426** [comment]
And under what circumstances does this occur?

**Comment by roberttaylor426** [comment]
I'd prefer not to close this issue due to inactivity - could you provide any more information around when this is happening?

**Comment by gnomff** [comment]
Hi Robert,

Sorry for the long delay - I have reconfigured my project dramatically and this issue seems to have disappeared. I will close it, but if it crops up again I will provide more details. Thanks for taking the time to look at it.
