### ISSUE TITLE
Please publish new version with fix for the left shift issue to the gradle plugins site.

### ISSUE THREAD

**Issue by steffenyount** [sourcemuse/GradleMongoPlugin#43]
This plugin is great but with gradle 3.2 I'm seeing tons of the following messages along with stack traces when I use it:

`The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.`

I see that there's already a patch that's been merged to remedy this issue.

Can you please post an updated artifact to the gradle plugins site?

**Comment by roberttaylor426** [comment]
I'll cut a new release today.

**Comment by roberttaylor426** [comment]
[Done](https://plugins.gradle.org/plugin/com.sourcemuse.mongo). Maven Central release will take a little while to propagate.

**Comment by steffenyount** [comment]
Fantastic. Thank you!
