### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by arudge** [sourcemuse/GradleMongoPlugin#45]
Hi Rob,

This is probably better done over email, but would you mind sharing the download statistics for the past two releases? 

Before digging into some more improvements, I'm wondering how actively this plugin is used.

**Comment by roberttaylor426** [comment]
Unfortunately [I don't think it's possible to get download stats from the Gradle Plugin Portal](https://discuss.gradle.org/t/plugin-portal-download-statistics/11609) at the moment.

I'm happy to share the download stats from central though:

## December 2016 (total ~1k)
Release | Count | Percent
----------- | -------- | ----------
0.13.0 | 402 | 40%
0.8.0 | 246 | 25%
0.14.0 | 176 | 18%
0.11.0 | 59 | 6%

## November 2016 (total ~1.4k)
Release | Count | Percent
----------- | -------- | ----------
0.13.0 | 882 | 59%
0.8.0 | 324 | 22%
0.11.0 | 92 | 6%

I've only included those releases which account for >5% of the download share.

**Comment by arudge** [comment]
Thanks!
