### ISSUE TITLE
start/stop mongo before/after test task?

### ISSUE THREAD

**Issue by yuhanz** [sourcemuse/GradleMongoPlugin#46]
I am trying to startMongo plugin before running test by:

<code>
task startMongo(type: Test) {
    runWithMongoDb = true
}

tasks.test.dependsOn("startMongo")
</code>

It ended up started mongo and then terminated it immediately before running the test.

How should it be setup correct?

**Comment by yuhanz** [comment]
This seems to work:

<code>
task startMongo(type: Test) {
    runWithMongoDb = true
}

test {
    doFirst {
        startMongo.execute()
    }

}
</code>

**Comment by roberttaylor426** [comment]
There is already a `startMongoDb` task added for you if you want to configure your build script in this way. You can remove the task definition.

Alternatively you can just say:
```
test {
    runWithMongoDb = true
}
```
