### ISSUE TITLE
The new plugin syntax fails for versions 1.0.1 and 1.0.2

### ISSUE THREAD

**Issue by joankaradimov** [sourcemuse/GradleMongoPlugin#49]
There appears to be something wrong in the distribution of the last two versions. The plugin fails to install if I use it with:

```groovy
plugins {
  id 'com.sourcemuse.mongo' version '1.0.2'
}
```

The error is:
```
* What went wrong:
A problem occurred evaluating root project '[...]'.
> A problem occurred configuring project '[...]'.
   > Could not resolve all files for configuration '[...]'.
      > Could not find gradle.plugin.com.sourcemuse.gradle.plugin:gradle-mongo-plugin:1.0.2.
        Searched in the following locations:
            https://repo1.maven.org/maven2/gradle/plugin/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.pom
            https://repo1.maven.org/maven2/gradle/plugin/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.jar
            https://plugins.gradle.org/m2/gradle/plugin/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.pom
            https://plugins.gradle.org/m2/gradle/plugin/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.jar
```

An identical error is present if the plugin is used [as seen here](https://plugins.gradle.org/plugin/com.sourcemuse.mongo) with:
```groovy
buildscript {
  // some repositories are listed here
  dependencies {
    classpath "gradle.plugin.com.sourcemuse.gradle.plugin:gradle-mongo-plugin:1.0.2"
  }
}

apply plugin: "com.sourcemuse.mongo"
```

However, everything runs fine if `gradle.plugin` is dropped and this is changed to:
```groovy
buildscript {
  // some repositories are listed here
  dependencies {
    classpath "com.sourcemuse.gradle.plugin:gradle-mongo-plugin:1.0.2"
  }
}

apply plugin: "com.sourcemuse.mongo"
```

**Comment by roberttaylor426** [comment]
Hmm that's odd. They're both [showing as uploaded|https://plugins.gradle.org/plugin/com.sourcemuse.mongo]. Could you try again?

**Comment by joankaradimov** [comment]
Yes, they are uploaded. But for some reason gradle tries to use [and gets a 404 for] this:
https://plugins.gradle.org/m2/gradle/plugin/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.pom

But this one appears to be the correct URL:
https://plugins.gradle.org/m2/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/1.0.2/gradle-mongo-plugin-1.0.2.pom

... same with the JARs.

**Comment by roberttaylor426** [comment]
It seems there was a problem with the version of the the `plugin-publish-plugin` I was using. I've bumped it to the latest (0.9.8) and now publishing seems to be working fine. 

Frustratingly although deleting and then republishing 1.0.1 seems have fixed URL resolution issues, I'm still seeing JAR URL resolution errors for 1.0.2, even after republish. 

In the interests of expediency I've release a version 1.0.3 and that seems to be working. Could you give that a try?

**Comment by joankaradimov** [comment]
> In the interests of expediency I've release a version 1.0.3 and that seems to be working. Could you give that a try?

Yes, I can confirm all is good now.
