### ISSUE TITLE
Mongo >3.4.10 doesn't work

### ISSUE THREAD

**Issue by lperdigaoatTel** [sourcemuse/GradleMongoPlugin#52]
After Mongo 3.4.10, Mongo has a different url pattern for download:
For example version 3.6 is:
http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.0.zip
while the plugin is looking for:
http://downloads.mongodb.org/win32/mongodb-win32-x86_64-3.6.0.zip

**Comment by dementiacs** [comment]
This has been corrected as part of the flapdoodle 2.0.0 release and so this plugin needs updating to use it.

**Comment by roberttaylor426** [comment]
This will be fixed as part of #51.

**Comment by roberttaylor426** [comment]
It turns out 3.6 isn't supported in Flapdoodle 2.0.0. [This PR](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/224) was merged recently, and as soon as they cut a new release I'll update and release the plugin accordingly.

**Comment by roberttaylor426** [comment]
1.0.4 is now out with support for Mongo 3.6.0.
