### ISSUE TITLE
Flapdoodle 2.0.0 is now available for Mongo 3.6 support.

### ISSUE THREAD

**Issue by dementiacs** [sourcemuse/GradleMongoPlugin#53]
I'd like to see this project updated to support Mongo 3.6

**Comment by roberttaylor426** [comment]
This will be addressed once #51 is merged.

**Comment by roberttaylor426** [comment]
#51 is merged, but unfortunately the latest release of Flapdoodle (2.0.0) does not support 3.6.

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/224 introduced the necessary changes, but they are yet to cut a new release. As soon as they do, I'll update the plugin accordingly.

**Comment by roberttaylor426** [comment]
1.0.4 is now out with support for 3.6.0.
