### ISSUE TITLE
Process started by running startMongo task has high CPU usage when idle

### ISSUE THREAD

**Issue by markaalvaro** [sourcemuse/GradleMongoPlugin#58]
Before upgrading from 1.0.0 to 1.0.6, a process called "extract-[UUID]-mongod" had a CPU usage of consistently less than 0.05%. After upgrading to 1.0.6, even when idle, the process sits around 90 to 100%. This tasks always starts after the startMongo task is run.  

When using mongod without the plugin for the same Mongo version (3.6.3), the CPU usage for the mongod process is less than 0.05%.

This has been observed with 

macOS Sierra Version 10.12.6
Gradle Version 4.6
mongoVersion = '3.6.3' (as specified by plugin configuration)

AND

macOS Yosemite 10.10
Gradle Version 4.6
mongoVersion = '3.6.3' (as specified by plugin configuration)

**Comment by roberttaylor426** [comment]
Courtesy of #59 this should now be fixed in the 1.0.7 release.
